/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

// ─── Caffeine framework role (MixinAuthorization) ────────────────────────────
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user'  : IDL.Null,
  'guest' : IDL.Null,
});

// ─── LBS4 custom role hierarchy ─────────────────────────────────────────────
export const Role = IDL.Variant({
  'Owner'   : IDL.Null,
  'CoOwner' : IDL.Null,
  'Staff'   : IDL.Null,
  'Builder' : IDL.Null,
});

export const UserStatus = IDL.Variant({
  'Active'    : IDL.Null,
  'Suspended' : IDL.Null,
});

// ─── Domain records ──────────────────────────────────────────────────────────
export const PublicUser = IDL.Record({
  'id'        : IDL.Nat,
  'username'  : IDL.Text,
  'role'      : Role,
  'status'    : UserStatus,
  'createdAt' : IDL.Int,
});

export const SessionData = IDL.Record({
  'token'     : IDL.Text,
  'userId'    : IDL.Nat,
  'username'  : IDL.Text,
  'role'      : Role,
  'createdAt' : IDL.Int,
  'expiresAt' : IDL.Int,
});

export const AuditLogEntry = IDL.Record({
  'id'          : IDL.Nat,
  'actorId'     : IDL.Nat,
  'action'      : IDL.Text,
  'performedBy' : IDL.Text,
  'targetUser'  : IDL.Opt(IDL.Text),
  'details'     : IDL.Text,
  'timestamp'   : IDL.Int,
});

export const FailedLoginAttempt = IDL.Record({
  'username'  : IDL.Text,
  'timestamp' : IDL.Int,
});

export const WebhookSettings = IDL.Record({
  'punishmentWebhookUrl' : IDL.Text,
});

export const LOARequest = IDL.Record({
  'id'              : IDL.Nat,
  'ign'             : IDL.Text,
  'discordUsername' : IDL.Text,
  'leaveDate'       : IDL.Text,
  'returnDate'      : IDL.Text,
  'submittedBy'     : IDL.Text,
  'timestamp'       : IDL.Int,
  'active'          : IDL.Bool,
});

export const PunishmentRecord = IDL.Record({
  'id'            : IDL.Nat,
  'playerIGN'     : IDL.Text,
  'altAccounts'   : IDL.Vec(IDL.Text),
  'category'      : IDL.Text,
  'offenseNumber' : IDL.Nat,
  'duration'      : IDL.Text,
  'reason'        : IDL.Text,
  'proofUrl'      : IDL.Text,
  'issuedBy'      : IDL.Text,
  'timestamp'     : IDL.Int,
  'appealed'      : IDL.Bool,
  'appealId'      : IDL.Opt(IDL.Nat),
});

// ─── Result variants ─────────────────────────────────────────────────────────
export const Result_1  = IDL.Variant({ 'ok' : IDL.Null,                    'err' : IDL.Text });
export const Result_2  = IDL.Variant({ 'ok' : PublicUser,                  'err' : IDL.Text });
export const Result_3  = IDL.Variant({ 'ok' : SessionData,                 'err' : IDL.Text });
export const Result_4  = IDL.Variant({ 'ok' : IDL.Nat,                     'err' : IDL.Text });
export const Result_5  = IDL.Variant({ 'ok' : IDL.Vec(PublicUser),         'err' : IDL.Text });
export const Result_6  = IDL.Variant({ 'ok' : IDL.Vec(AuditLogEntry),      'err' : IDL.Text });
export const Result_7  = IDL.Variant({ 'ok' : IDL.Vec(FailedLoginAttempt), 'err' : IDL.Text });
export const Result_8  = IDL.Variant({ 'ok' : WebhookSettings,             'err' : IDL.Text });
export const Result_9  = IDL.Variant({ 'ok' : IDL.Vec(LOARequest),         'err' : IDL.Text });
export const Result_10 = IDL.Variant({ 'ok' : IDL.Vec(PunishmentRecord),   'err' : IDL.Text });

export const idlService = IDL.Service({
  // ── MixinAuthorization (Caffeine framework) ──────────────────────────────
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole'    : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin'        : IDL.Func([], [IDL.Bool], ['query']),

  // ── Custom auth ──────────────────────────────────────────────────────────
  'loginWithCredentials' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'validateSession'      : IDL.Func([IDL.Text], [Result_2], []),
  'logoutSession'        : IDL.Func([IDL.Text], [], []),

  // ── User management ──────────────────────────────────────────────────────
  'createUser'     : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [Result_4], []),
  'removeUser'     : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'suspendUser'    : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'activateUser'   : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'updateUserRole' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_1], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'getAllUsers'     : IDL.Func([IDL.Text], [Result_5], []),

  // ── Audit log ────────────────────────────────────────────────────────────
  'getAuditLog'            : IDL.Func([IDL.Text], [Result_6], []),
  'getFailedLoginAttempts' : IDL.Func([IDL.Text], [Result_7], []),

  // ── Webhook config ───────────────────────────────────────────────────────
  'getWebhookConfig' : IDL.Func([IDL.Text], [Result_8], []),
  'setWebhookConfig' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),

  // ── LOA ──────────────────────────────────────────────────────────────────
  'submitLOARequest'  : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Result_4], []),
  'getAllLOARequests'  : IDL.Func([IDL.Text], [Result_9], []),
  'deactivateLOA'     : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),

  // ── Punishments ──────────────────────────────────────────────────────────
  'submitPunishmentLog' : IDL.Func(
    [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
    [Result_4],
    [],
  ),
  'getAllPunishmentLogs'  : IDL.Func([IDL.Text], [Result_10], []),
  'getPunishmentLogCount' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user'  : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'Owner'   : IDL.Null,
    'CoOwner' : IDL.Null,
    'Staff'   : IDL.Null,
    'Builder' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'Active'    : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const PublicUser = IDL.Record({
    'id'        : IDL.Nat,
    'username'  : IDL.Text,
    'role'      : Role,
    'status'    : UserStatus,
    'createdAt' : IDL.Int,
  });
  const SessionData = IDL.Record({
    'token'     : IDL.Text,
    'userId'    : IDL.Nat,
    'username'  : IDL.Text,
    'role'      : Role,
    'createdAt' : IDL.Int,
    'expiresAt' : IDL.Int,
  });
  const AuditLogEntry = IDL.Record({
    'id'          : IDL.Nat,
    'actorId'     : IDL.Nat,
    'action'      : IDL.Text,
    'performedBy' : IDL.Text,
    'targetUser'  : IDL.Opt(IDL.Text),
    'details'     : IDL.Text,
    'timestamp'   : IDL.Int,
  });
  const FailedLoginAttempt = IDL.Record({
    'username'  : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const WebhookSettings = IDL.Record({
    'punishmentWebhookUrl' : IDL.Text,
  });
  const LOARequest = IDL.Record({
    'id'              : IDL.Nat,
    'ign'             : IDL.Text,
    'discordUsername' : IDL.Text,
    'leaveDate'       : IDL.Text,
    'returnDate'      : IDL.Text,
    'submittedBy'     : IDL.Text,
    'timestamp'       : IDL.Int,
    'active'          : IDL.Bool,
  });
  const PunishmentRecord = IDL.Record({
    'id'            : IDL.Nat,
    'playerIGN'     : IDL.Text,
    'altAccounts'   : IDL.Vec(IDL.Text),
    'category'      : IDL.Text,
    'offenseNumber' : IDL.Nat,
    'duration'      : IDL.Text,
    'reason'        : IDL.Text,
    'proofUrl'      : IDL.Text,
    'issuedBy'      : IDL.Text,
    'timestamp'     : IDL.Int,
    'appealed'      : IDL.Bool,
    'appealId'      : IDL.Opt(IDL.Nat),
  });
  const Result_1  = IDL.Variant({ 'ok' : IDL.Null,                    'err' : IDL.Text });
  const Result_2  = IDL.Variant({ 'ok' : PublicUser,                  'err' : IDL.Text });
  const Result_3  = IDL.Variant({ 'ok' : SessionData,                 'err' : IDL.Text });
  const Result_4  = IDL.Variant({ 'ok' : IDL.Nat,                     'err' : IDL.Text });
  const Result_5  = IDL.Variant({ 'ok' : IDL.Vec(PublicUser),         'err' : IDL.Text });
  const Result_6  = IDL.Variant({ 'ok' : IDL.Vec(AuditLogEntry),      'err' : IDL.Text });
  const Result_7  = IDL.Variant({ 'ok' : IDL.Vec(FailedLoginAttempt), 'err' : IDL.Text });
  const Result_8  = IDL.Variant({ 'ok' : WebhookSettings,             'err' : IDL.Text });
  const Result_9  = IDL.Variant({ 'ok' : IDL.Vec(LOARequest),         'err' : IDL.Text });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Vec(PunishmentRecord),   'err' : IDL.Text });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole'    : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin'        : IDL.Func([], [IDL.Bool], ['query']),

    'loginWithCredentials' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'validateSession'      : IDL.Func([IDL.Text], [Result_2], []),
    'logoutSession'        : IDL.Func([IDL.Text], [], []),

    'createUser'     : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [Result_4], []),
    'removeUser'     : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'suspendUser'    : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'activateUser'   : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'updateUserRole' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_1], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'getAllUsers'     : IDL.Func([IDL.Text], [Result_5], []),

    'getAuditLog'            : IDL.Func([IDL.Text], [Result_6], []),
    'getFailedLoginAttempts' : IDL.Func([IDL.Text], [Result_7], []),

    'getWebhookConfig' : IDL.Func([IDL.Text], [Result_8], []),
    'setWebhookConfig' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),

    'submitLOARequest'  : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Result_4], []),
    'getAllLOARequests'  : IDL.Func([IDL.Text], [Result_9], []),
    'deactivateLOA'     : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),

    'submitPunishmentLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Result_4],
      [],
    ),
    'getAllPunishmentLogs'   : IDL.Func([IDL.Text], [Result_10], []),
    'getPunishmentLogCount' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };
