/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiscordSessionData {
  'token' : string,
  'discordId' : string,
  'username' : string,
  'avatar' : string,
  'role' : string,
  'createdAt' : bigint,
}
export interface LOARequest {
  'id' : bigint,
  'ign' : string,
  'active' : boolean,
  'submittedBy' : string,
  'timestamp' : bigint,
  'discordUsername' : string,
  'leaveDate' : string,
  'returnDate' : string,
}
export interface PublicUser {
  'id' : UserId,
  'username' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export interface PunishmentLog {
  'id' : bigint,
  'ign' : string,
  'rnd' : string,
  'offenseNumber' : bigint,
  'submittedBy' : string,
  'timestamp' : bigint,
  'proof' : string,
}
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : PublicUser } |
  { 'err' : string };
export type Result_3 = { 'ok' : WebhookConfig } |
  { 'err' : string };
export type Result_4 = { 'ok' : Array<PublicUser> } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<PunishmentLog> } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<LOARequest> } |
  { 'err' : string };
export type Result_7 = { 'ok' : UserId } |
  { 'err' : string };
export type Result_8 = { 'ok' : DiscordSessionData } |
  { 'err' : string };
export type Role = { 'CoOwner' : null } |
  { 'StaffBuilder' : null } |
  { 'Owner' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = bigint;
export interface UserProfile {
  'ign' : string,
  'username' : string,
  'role' : Role,
  'discordUsername' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebhookConfig {
  'loaWebhookUrl' : string,
  'punishmentWebhookUrl' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<[string, string], Result_1>,
  'createStaffAccount' : ActorMethod<
    [Principal, string, string, Role],
    Result_7
  >,
  'deactivateLOA' : ActorMethod<[bigint], Result_1>,
  'discordCallback' : ActorMethod<[string, string], Result_8>,
  'discordLogout' : ActorMethod<[string], undefined>,
  'dummyTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'getActiveLOACount' : ActorMethod<[], bigint>,
  'getAllLOARequests' : ActorMethod<[], Result_6>,
  'getAllPunishmentLogs' : ActorMethod<[], Result_5>,
  'getAllUsers' : ActorMethod<[], Result_4>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<[], Result_2>,
  'getDiscordSession' : ActorMethod<[string], [] | [DiscordSessionData]>,
  'getPunishmentLogCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebhookConfig' : ActorMethod<[], Result_3>,
  'initializeBackend' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], Result_2>,
  'logout' : ActorMethod<[], Result_1>,
  'promoteUser' : ActorMethod<[Principal, Role], Result_1>,
  'removeStaffAccount' : ActorMethod<[Principal], Result_1>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setWebhookConfig' : ActorMethod<[string, string], Result_1>,
  'submitLOARequest' : ActorMethod<[string, string, string, string], Result>,
  'submitPunishmentLog' : ActorMethod<[string, string, bigint, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];