/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Role = IDL.Variant({
  'CoOwner' : IDL.Null,
  'StaffBuilder' : IDL.Null,
  'Owner' : IDL.Null,
});
export const UserId = IDL.Nat;
export const Result_7 = IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const LOARequest = IDL.Record({
  'id' : IDL.Nat,
  'ign' : IDL.Text,
  'active' : IDL.Bool,
  'submittedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'discordUsername' : IDL.Text,
  'leaveDate' : IDL.Text,
  'returnDate' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(LOARequest),
  'err' : IDL.Text,
});
export const PunishmentLog = IDL.Record({
  'id' : IDL.Nat,
  'ign' : IDL.Text,
  'rnd' : IDL.Text,
  'offenseNumber' : IDL.Nat,
  'submittedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'proof' : IDL.Text,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(PunishmentLog),
  'err' : IDL.Text,
});
export const PublicUser = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(PublicUser),
  'err' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'ign' : IDL.Text,
  'username' : IDL.Text,
  'role' : Role,
  'discordUsername' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : PublicUser, 'err' : IDL.Text });
export const WebhookConfig = IDL.Record({
  'loaWebhookUrl' : IDL.Text,
  'punishmentWebhookUrl' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : WebhookConfig, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const DiscordSessionData = IDL.Record({
  'token' : IDL.Text,
  'discordId' : IDL.Text,
  'username' : IDL.Text,
  'avatar' : IDL.Text,
  'role' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Result_8 = IDL.Variant({ 'ok' : DiscordSessionData, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'createStaffAccount' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, Role],
      [Result_7],
      [],
    ),
  'deactivateLOA' : IDL.Func([IDL.Nat], [Result_1], []),
  'discordCallback' : IDL.Func([IDL.Text, IDL.Text], [Result_8], []),
  'discordLogout' : IDL.Func([IDL.Text], [], []),
  'dummyTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'getActiveLOACount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllLOARequests' : IDL.Func([], [Result_6], ['query']),
  'getAllPunishmentLogs' : IDL.Func([], [Result_5], ['query']),
  'getAllUsers' : IDL.Func([], [Result_4], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([], [Result_2], ['query']),
  'getDiscordSession' : IDL.Func([IDL.Text], [IDL.Opt(DiscordSessionData)], ['query']),
  'getPunishmentLogCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebhookConfig' : IDL.Func([], [Result_3], ['query']),
  'initializeBackend' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'logout' : IDL.Func([], [Result_1], []),
  'promoteUser' : IDL.Func([IDL.Principal, Role], [Result_1], []),
  'removeStaffAccount' : IDL.Func([IDL.Principal], [Result_1], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setWebhookConfig' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'submitLOARequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'submitPunishmentLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Role = IDL.Variant({
    'CoOwner' : IDL.Null,
    'StaffBuilder' : IDL.Null,
    'Owner' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const Result_7 = IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const LOARequest = IDL.Record({
    'id' : IDL.Nat,
    'ign' : IDL.Text,
    'active' : IDL.Bool,
    'submittedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'discordUsername' : IDL.Text,
    'leaveDate' : IDL.Text,
    'returnDate' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(LOARequest),
    'err' : IDL.Text,
  });
  const PunishmentLog = IDL.Record({
    'id' : IDL.Nat,
    'ign' : IDL.Text,
    'rnd' : IDL.Text,
    'offenseNumber' : IDL.Nat,
    'submittedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'proof' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Vec(PunishmentLog),
    'err' : IDL.Text,
  });
  const PublicUser = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Vec(PublicUser),
    'err' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'ign' : IDL.Text,
    'username' : IDL.Text,
    'role' : Role,
    'discordUsername' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : PublicUser, 'err' : IDL.Text });
  const WebhookConfig = IDL.Record({
    'loaWebhookUrl' : IDL.Text,
    'punishmentWebhookUrl' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : WebhookConfig, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const DiscordSessionData = IDL.Record({
    'token' : IDL.Text,
    'discordId' : IDL.Text,
    'username' : IDL.Text,
    'avatar' : IDL.Text,
    'role' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Result_8 = IDL.Variant({ 'ok' : DiscordSessionData, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'createStaffAccount' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, Role],
        [Result_7],
        [],
      ),
    'deactivateLOA' : IDL.Func([IDL.Nat], [Result_1], []),
    'discordCallback' : IDL.Func([IDL.Text, IDL.Text], [Result_8], []),
    'discordLogout' : IDL.Func([IDL.Text], [], []),
    'dummyTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'getActiveLOACount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllLOARequests' : IDL.Func([], [Result_6], ['query']),
    'getAllPunishmentLogs' : IDL.Func([], [Result_5], ['query']),
    'getAllUsers' : IDL.Func([], [Result_4], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([], [Result_2], ['query']),
    'getDiscordSession' : IDL.Func([IDL.Text], [IDL.Opt(DiscordSessionData)], ['query']),
    'getPunishmentLogCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebhookConfig' : IDL.Func([], [Result_3], ['query']),
    'initializeBackend' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'logout' : IDL.Func([], [Result_1], []),
    'promoteUser' : IDL.Func([IDL.Principal, Role], [Result_1], []),
    'removeStaffAccount' : IDL.Func([IDL.Principal], [Result_1], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setWebhookConfig' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'submitLOARequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'submitPunishmentLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };