/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";

// ─── Helpers ─────────────────────────────────────────────────────────────────

export interface Some<T> { __kind__: "Some"; value: T; }
export interface None { __kind__: "None"; }
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> { return { __kind__: "Some", value }; }
function none(): None { return { __kind__: "None" }; }
function isNone<T>(option: Option<T>): option is None { return option.__kind__ === "None"; }
function isSome<T>(option: Option<T>): option is Some<T> { return option.__kind__ === "Some"; }
function unwrap<T>(option: Option<T>): T {
  if (isNone(option)) throw new Error("unwrap: none");
  return option.value;
}
function candid_some<T>(value: T): [T] { return [value]; }
function candid_none<T>(): [] { return []; }
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
  return arg == null ? undefined : arg;
}

export class ExternalBlob {
  _blob?: Uint8Array<ArrayBuffer> | null;
  directURL: string;
  onProgress?: (percentage: number) => void = undefined;
  private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
    if (blob) { this._blob = blob; }
    this.directURL = directURL;
  }
  static fromURL(url: string): ExternalBlob { return new ExternalBlob(url, null); }
  static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
    const url = URL.createObjectURL(new Blob([new Uint8Array(blob)], { type: 'application/octet-stream' }));
    return new ExternalBlob(url, blob);
  }
  public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
    if (this._blob) return this._blob;
    const response = await fetch(this.directURL);
    const blob = await response.blob();
    this._blob = new Uint8Array(await blob.arrayBuffer());
    return this._blob;
  }
  public getDirectURL(): string { return this.directURL; }
  public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
    this.onProgress = onProgress;
    return this;
  }
}

// ─── Enums ───────────────────────────────────────────────────────────────────

export enum Role {
  Owner   = "Owner",
  CoOwner = "CoOwner",
  Staff   = "Staff",
  Builder = "Builder",
}

export enum UserStatus {
  Active    = "Active",
  Suspended = "Suspended",
}

export enum UserRole {
  admin = "admin",
  user  = "user",
  guest = "guest",
}

// ─── TypeScript interfaces for Candid types ──────────────────────────────────

export interface PublicUser {
  id: bigint;
  username: string;
  role: Role;
  status: UserStatus;
  createdAt: bigint;
}

export interface SessionData {
  token: string;
  userId: bigint;
  username: string;
  role: Role;
  createdAt: bigint;
  expiresAt: bigint;
}

export interface AuditLogEntry {
  id: bigint;
  actorId: bigint;
  action: string;
  performedBy: string;
  targetUser: string | null;
  details: string;
  timestamp: bigint;
}

export interface FailedLoginAttempt {
  username: string;
  timestamp: bigint;
}

export interface WebhookSettings {
  punishmentWebhookUrl: string;
}

export interface LOARequest {
  id: bigint;
  ign: string;
  discordUsername: string;
  leaveDate: string;
  returnDate: string;
  submittedBy: string;
  timestamp: bigint;
  active: boolean;
}

export interface PunishmentRecord {
  id: bigint;
  playerIGN: string;
  altAccounts: Array<string>;
  category: string;
  offenseNumber: bigint;
  duration: string;
  reason: string;
  proofUrl: string;
  issuedBy: string;
  timestamp: bigint;
  appealed: boolean;
  appealId: bigint | null;
}

// ─── Result types ─────────────────────────────────────────────────────────────

export type Result_1  = { __kind__: "ok"; ok: null }                      | { __kind__: "err"; err: string };
export type Result_2  = { __kind__: "ok"; ok: PublicUser }                | { __kind__: "err"; err: string };
export type Result_3  = { __kind__: "ok"; ok: SessionData }               | { __kind__: "err"; err: string };
export type Result_4  = { __kind__: "ok"; ok: bigint }                    | { __kind__: "err"; err: string };
export type Result_5  = { __kind__: "ok"; ok: Array<PublicUser> }         | { __kind__: "err"; err: string };
export type Result_6  = { __kind__: "ok"; ok: Array<AuditLogEntry> }      | { __kind__: "err"; err: string };
export type Result_7  = { __kind__: "ok"; ok: Array<FailedLoginAttempt> } | { __kind__: "err"; err: string };
export type Result_8  = { __kind__: "ok"; ok: WebhookSettings }           | { __kind__: "err"; err: string };
export type Result_9  = { __kind__: "ok"; ok: Array<LOARequest> }         | { __kind__: "err"; err: string };
export type Result_10 = { __kind__: "ok"; ok: Array<PunishmentRecord> }   | { __kind__: "err"; err: string };

// ─── Candid variant conversion helpers ───────────────────────────────────────

function fromCandidResult_1(value: { ok: null } | { err: string }): Result_1 {
  return "ok" in value ? { __kind__: "ok", ok: value.ok } : { __kind__: "err", err: value.err };
}
function fromCandidResult_4(value: { ok: bigint } | { err: string }): Result_4 {
  return "ok" in value ? { __kind__: "ok", ok: value.ok } : { __kind__: "err", err: value.err };
}
function fromCandidRole(value: { Owner: null } | { CoOwner: null } | { Staff: null } | { Builder: null }): Role {
  if ("Owner"   in value) return Role.Owner;
  if ("CoOwner" in value) return Role.CoOwner;
  if ("Staff"   in value) return Role.Staff;
  return Role.Builder;
}
function toCandidRole(value: Role): { Owner: null } | { CoOwner: null } | { Staff: null } | { Builder: null } {
  if (value === Role.Owner)   return { Owner:   null };
  if (value === Role.CoOwner) return { CoOwner: null };
  if (value === Role.Staff)   return { Staff:   null };
  return { Builder: null };
}
function fromCandidUserStatus(value: { Active: null } | { Suspended: null }): UserStatus {
  return "Active" in value ? UserStatus.Active : UserStatus.Suspended;
}
function fromCandidUserRole(value: { admin: null } | { user: null } | { guest: null }): UserRole {
  if ("admin" in value) return UserRole.admin;
  if ("user"  in value) return UserRole.user;
  return UserRole.guest;
}
function toCandidUserRole(value: UserRole): { admin: null } | { user: null } | { guest: null } {
  if (value === UserRole.admin) return { admin: null };
  if (value === UserRole.user)  return { user:  null };
  return { guest: null };
}
function fromCandidPublicUser(value: any): PublicUser {
  return {
    id: value.id,
    username: value.username,
    role: fromCandidRole(value.role),
    status: fromCandidUserStatus(value.status),
    createdAt: value.createdAt,
  };
}
function fromCandidSessionData(value: any): SessionData {
  return {
    token: value.token,
    userId: value.userId,
    username: value.username,
    role: fromCandidRole(value.role),
    createdAt: value.createdAt,
    expiresAt: value.expiresAt,
  };
}
function fromCandidAuditLogEntry(value: any): AuditLogEntry {
  return {
    id: value.id,
    actorId: value.actorId,
    action: value.action,
    performedBy: value.performedBy,
    targetUser: value.targetUser.length > 0 ? value.targetUser[0] : null,
    details: value.details,
    timestamp: value.timestamp,
  };
}
function fromCandidPunishmentRecord(value: any): PunishmentRecord {
  return {
    id: value.id,
    playerIGN: value.playerIGN,
    altAccounts: value.altAccounts,
    category: value.category,
    offenseNumber: value.offenseNumber,
    duration: value.duration,
    reason: value.reason,
    proofUrl: value.proofUrl,
    issuedBy: value.issuedBy,
    timestamp: value.timestamp,
    appealed: value.appealed,
    appealId: value.appealId.length > 0 ? value.appealId[0] : null,
  };
}
function fromCandidResult_2(value: any): Result_2 {
  return "ok" in value
    ? { __kind__: "ok", ok: fromCandidPublicUser(value.ok) }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_3(value: any): Result_3 {
  return "ok" in value
    ? { __kind__: "ok", ok: fromCandidSessionData(value.ok) }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_5(value: any): Result_5 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok.map(fromCandidPublicUser) }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_6(value: any): Result_6 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok.map(fromCandidAuditLogEntry) }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_7(value: any): Result_7 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_8(value: any): Result_8 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_9(value: any): Result_9 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok }
    : { __kind__: "err", err: value.err };
}
function fromCandidResult_10(value: any): Result_10 {
  return "ok" in value
    ? { __kind__: "ok", ok: value.ok.map(fromCandidPunishmentRecord) }
    : { __kind__: "err", err: value.err };
}

// ─── Backend interface ────────────────────────────────────────────────────────

export interface backendInterface {
  // MixinAuthorization
  _initializeAccessControlWithSecret(secret: string): Promise<void>;
  assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
  getCallerUserRole(): Promise<UserRole>;
  isCallerAdmin(): Promise<boolean>;

  // Custom auth
  loginWithCredentials(username: string, passwordHash: string): Promise<Result_3>;
  validateSession(token: string): Promise<Result_2>;
  logoutSession(token: string): Promise<void>;

  // User management
  createUser(token: string, username: string, passwordHash: string, role: Role): Promise<Result_4>;
  removeUser(token: string, targetUsername: string): Promise<Result_1>;
  suspendUser(token: string, targetUsername: string): Promise<Result_1>;
  activateUser(token: string, targetUsername: string): Promise<Result_1>;
  updateUserRole(token: string, targetUsername: string, newRole: Role): Promise<Result_1>;
  changePassword(token: string, oldPasswordHash: string, newPasswordHash: string): Promise<Result_1>;
  getAllUsers(token: string): Promise<Result_5>;

  // Audit log
  getAuditLog(token: string): Promise<Result_6>;
  getFailedLoginAttempts(token: string): Promise<Result_7>;

  // Webhook
  getWebhookConfig(token: string): Promise<Result_8>;
  setWebhookConfig(token: string, punishmentUrl: string): Promise<Result_1>;

  // LOA
  submitLOARequest(token: string, ign: string, discordUsername: string, leaveDate: string, returnDate: string): Promise<Result_4>;
  getAllLOARequests(token: string): Promise<Result_9>;
  deactivateLOA(token: string, loaId: bigint): Promise<Result_1>;

  // Punishments
  submitPunishmentLog(token: string, playerIGN: string, category: string, offenseNumber: bigint, duration: string, reason: string, proofUrl: string, altAccounts: string[]): Promise<Result_4>;
  getAllPunishmentLogs(token: string): Promise<Result_10>;
  getPunishmentLogCount(): Promise<bigint>;
}

// ─── Backend class ───────────────────────────────────────────────────────────

export class Backend implements backendInterface {
  constructor(
    private actor: ActorSubclass<_SERVICE>,
    private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
    private processError?: (error: unknown) => never,
  ) {}

  private async call<T>(fn: () => Promise<T>): Promise<T> {
    if (this.processError) {
      try {
        return await fn();
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    }
    return fn();
  }

  // ── MixinAuthorization ───────────────────────────────────────────────
  async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
    return this.call(() => this.actor._initializeAccessControlWithSecret(arg0));
  }
  async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
    return this.call(() => this.actor.assignCallerUserRole(arg0, toCandidUserRole(arg1)));
  }
  async getCallerUserRole(): Promise<UserRole> {
    return this.call(async () => fromCandidUserRole(await this.actor.getCallerUserRole()));
  }
  async isCallerAdmin(): Promise<boolean> {
    return this.call(() => this.actor.isCallerAdmin());
  }

  // ── Custom auth ──────────────────────────────────────────────────────
  async loginWithCredentials(username: string, passwordHash: string): Promise<Result_3> {
    return this.call(async () => fromCandidResult_3(await this.actor.loginWithCredentials(username, passwordHash)));
  }
  async validateSession(token: string): Promise<Result_2> {
    return this.call(async () => fromCandidResult_2(await this.actor.validateSession(token)));
  }
  async logoutSession(token: string): Promise<void> {
    return this.call(() => this.actor.logoutSession(token));
  }

  // ── User management ─────────────────────────────────────────────────
  async createUser(token: string, username: string, passwordHash: string, role: Role): Promise<Result_4> {
    return this.call(async () => fromCandidResult_4(await this.actor.createUser(token, username, passwordHash, toCandidRole(role))));
  }
  async removeUser(token: string, targetUsername: string): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.removeUser(token, targetUsername)));
  }
  async suspendUser(token: string, targetUsername: string): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.suspendUser(token, targetUsername)));
  }
  async activateUser(token: string, targetUsername: string): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.activateUser(token, targetUsername)));
  }
  async updateUserRole(token: string, targetUsername: string, newRole: Role): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.updateUserRole(token, targetUsername, toCandidRole(newRole))));
  }
  async changePassword(token: string, oldPasswordHash: string, newPasswordHash: string): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.changePassword(token, oldPasswordHash, newPasswordHash)));
  }
  async getAllUsers(token: string): Promise<Result_5> {
    return this.call(async () => fromCandidResult_5(await this.actor.getAllUsers(token)));
  }

  // ── Audit log ───────────────────────────────────────────────────────────
  async getAuditLog(token: string): Promise<Result_6> {
    return this.call(async () => fromCandidResult_6(await this.actor.getAuditLog(token)));
  }
  async getFailedLoginAttempts(token: string): Promise<Result_7> {
    return this.call(async () => fromCandidResult_7(await this.actor.getFailedLoginAttempts(token)));
  }

  // ── Webhook config ─────────────────────────────────────────────────────
  async getWebhookConfig(token: string): Promise<Result_8> {
    return this.call(async () => fromCandidResult_8(await this.actor.getWebhookConfig(token)));
  }
  async setWebhookConfig(token: string, punishmentUrl: string): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.setWebhookConfig(token, punishmentUrl)));
  }

  // ── LOA ──────────────────────────────────────────────────────────────────
  async submitLOARequest(token: string, ign: string, discordUsername: string, leaveDate: string, returnDate: string): Promise<Result_4> {
    return this.call(async () => fromCandidResult_4(await this.actor.submitLOARequest(token, ign, discordUsername, leaveDate, returnDate)));
  }
  async getAllLOARequests(token: string): Promise<Result_9> {
    return this.call(async () => fromCandidResult_9(await this.actor.getAllLOARequests(token)));
  }
  async deactivateLOA(token: string, loaId: bigint): Promise<Result_1> {
    return this.call(async () => fromCandidResult_1(await this.actor.deactivateLOA(token, loaId)));
  }

  // ── Punishments ─────────────────────────────────────────────────────────
  async submitPunishmentLog(token: string, playerIGN: string, category: string, offenseNumber: bigint, duration: string, reason: string, proofUrl: string, altAccounts: string[]): Promise<Result_4> {
    return this.call(async () => fromCandidResult_4(await this.actor.submitPunishmentLog(token, playerIGN, category, offenseNumber, duration, reason, proofUrl, altAccounts)));
  }
  async getAllPunishmentLogs(token: string): Promise<Result_10> {
    return this.call(async () => fromCandidResult_10(await this.actor.getAllPunishmentLogs(token)));
  }
  async getPunishmentLogCount(): Promise<bigint> {
    return this.call(() => this.actor.getPunishmentLogCount());
  }
}

// ─── Actor factory ────────────────────────────────────────────────────────────

export interface CreateActorOptions {
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: ActorConfig;
  processError?: (error: unknown) => never;
}

export function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  options: CreateActorOptions = {},
): Backend {
  const agent = options.agent || HttpAgent.createSync({ ...options.agentOptions });
  if (options.agent && options.agentOptions) {
    console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
  }
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId,
    ...options.actorOptions,
  });
  return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
